### ISSUE TITLE
np.float is deprecated

### ISSUE THREAD

**Issue by TheSl0thzilla** [dshean/imview#4]
gmtColormap.py raises an error: np.float is deprecated in numpy 1.20. Should either use 'float' or 'np.float64'. Might be worth updating.

**Comment by dshean** [comment]
Thanks @TheSl0thzilla.  Do you mind submitting a PR?  I think `float` should be fine.

**Comment by dshean** [comment]
Fixed in https://github.com/dshean/imview/commit/1425f0a7eb611ce41d44e9f9d63554eb711ad482
