### ISSUE TITLE
Error with the PyPi latest 

### ISSUE THREAD

**Issue by LaTortueSolitaire** [dshean/imview#5]
Hi,

Installing from Pypi with:
`pip install imview`

I get the error:

> Traceback (most recent call last):
>   File "./demcoreg/dem_align.py", line 21, in <module>
>     from imview.lib import pltlib
>   File "/home/latortue/anaconda3/envs/demcoreg_env/lib/python3.7/site-packages/imview/lib/pltlib.py", line 139
>     print "Polygon support not yet implemented"
>                                               ^
> SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Polygon support not yet implemented")?

But it works fine when I install imview module from source with this repository.

**Comment by dshean** [comment]
Hi @LaTortueSolitaire.  Thanks for the report.  This is likely due to the fact that I haven't updated the PyPi releases since 2019!  It's on the to do list, but glad you were able to install directly from latest github source (recommended approach for now).

**Comment by dshean** [comment]
OK, I just pushed up the latest distributions to PyPi.  Hopefully that should resolve these old Python2->3 issues.  I still recommend installing from latest source, as I have not been keeping up with official releases for these packages, and most recent commits are small maintenance fixes.

**Comment by LaTortueSolitaire** [comment]
Good to know. Thanks for your quick reply. 
Just as a side note it was the same for the demcoreg and pygeotool packages(working from source).
